### ISSUE TITLE
InvalidCast Exception on startup

### ISSUE THREAD

**Issue by ymor** [aws-observability/aws-otel-dotnet-instrumentation#82]
Image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/observability/adot-autoinstrumentation-dotnet:v1.1.0

Logs
```
info: AWS.Distro.OpenTelemetry.AutoInstrumentation.Plugin[0]
      AWS Application Signals enabled
info: AWS.Distro.OpenTelemetry.AutoInstrumentation.SamplerUtil[0]
      XRay Sampler Endpoint: http://cloudwatch-agent.amazon-cloudwatch:2000
info: AWS.Distro.OpenTelemetry.AutoInstrumentation.SamplerUtil[0]
      XRay Sampler Polling Interval:: 300
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributeGenerator.GetDbConnection(Activity span)
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributeGenerator.SetRemoteResourceTypeAndIdentifier(Activity span, ActivityTagsCollection attributes)
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributeGenerator.GenerateDependencyMetricAttributes(Activity span, Resource resource)
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributeGenerator.GenerateMetricAttributeMapFromSpan(Activity span, Resource resource)
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributesSpanProcessor.AddMetricAttributes(Activity span)
 at AWS.Distro.OpenTelemetry.AutoInstrumentation.AwsMetricAttributesSpanProcessor.OnEnd(Activity activity)
 at OpenTelemetry.CompositeProcessor`1.OnEnd(T data)
 at OpenTelemetry.Trace.TracerProviderSdk.<>c__DisplayClass12_1.<.ctor>b__11(Activity activity)
 at System.Diagnostics.ActivitySource.<>c.<NotifyActivityStop>b__25_0(ActivityListener listener, Object obj)
 at System.Diagnostics.SynchronizedList`1.EnumWithAction(Action`2 action, Object arg)
 at System.Diagnostics.ActivitySource.NotifyActivityStop(Activity activity)
 at System.Diagnostics.Activity.Stop()
 at OpenTelemetry.Instrumentation.StackExchangeRedis.Implementation.RedisProfilerEntryToActivityConverter.ProfilerCommandToActivity(Activity parentActivity, IProfiledCommand command, StackExchangeRedisInstrumentationOptions options)
 at OpenTelemetry.Instrumentation.StackExchangeRedis.Implementation.RedisProfilerEntryToActivityConverter.DrainSession(Activity parentActivity, IEnumerable`1 sessionCommands, StackExchangeRedisInstrumentationOptions options)
 at OpenTelemetry.Instrumentation.StackExchangeRedis.StackExchangeRedisConnectionInstrumentation.Flush()
 at OpenTelemetry.Instrumentation.StackExchangeRedis.StackExchangeRedisConnectionInstrumentation.DrainEntries(Object state)
 at System.Threading.Thread.StartCallback()

```

This exception occurs in my container as soon as it starts.  The port number used in the redis connection string is 6379.
Let me know if you need any extra details.

**Comment by AsakerMohd** [comment]
This should be fixed now. Fix should be available on the next release.
